const handleError = require("./handleError")

const createCustomer=async()=>{
    try{
        
    }catch(error){
        handleError(error,res)
    }
}